'use client';
import Head from 'next/head';
import { lazy } from 'react';
let RemoteTitle = () => null;
if (process.browser) {
  //useCustomHook = require('shop/customHook').default;
  RemoteTitle = lazy(() => {
    return import('core/Modal');
  });
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RemoteTitle open={true} handleClose={() => ''} />
      </main>
    </>
  );
}
